require 'prodam/idealize'

include Prodam::Idealize

(Usuario.new nome_usuario: "p001264" , nome: "Isabela Xavier de Castro Catarino"            , email: "isabela@prodam.am.gov.br"                          ).save senha: "_001264"
(Usuario.new nome_usuario: "p001379" , nome: "Éldio Filho Almeida Barbosa"                  , email: "eldio@prodam.am.gov.br"                            ).save senha: "_001379"
(Usuario.new nome_usuario: "p000591" , nome: "Erlon Angelin Benjó"                          , email: "erlon@prodam.am.gov.br"                            ).save senha: "_000591"
(Usuario.new nome_usuario: "p001392" , nome: "Simone da Graça Campelo"                      , email: "sgraca@prodam.am.gov.br"                           ).save senha: "_001392"
(Usuario.new nome_usuario: "p001339" , nome: "Thales Gomes Wanderley"                       , email: "thales.wanderley@prodam.am.gov.br"                 ).save senha: "_001339"
(Usuario.new nome_usuario: "p001115" , nome: "Jorge Rezalla Bouez Abrahim"                  , email: "informatica@poligmestrinho.am.gov.br"              ).save senha: "_001115"
(Usuario.new nome_usuario: "p001079" , nome: "Jander Cleison da Silva Carvalho"             , email: "assessoriainfo@policodajas.am.gov.br"              ).save senha: "_001079"
(Usuario.new nome_usuario: "p000821" , nome: "Antonio Francisco Sales de Farias"            , email: "farias@prodam.am.gov.br"                           ).save senha: "_000821"
(Usuario.new nome_usuario: "p000146" , nome: "Aristóbulo Angelim de Araújo"                 , email: "ari@prodam.am.gov.br"                              ).save senha: "_000146"
(Usuario.new nome_usuario: "p001011" , nome: "Daniel Tadeu Martinez Castello Branco"        , email: "dmartinez@prodam.am.gov.br"                        ).save senha: "_001011"
(Usuario.new nome_usuario: "p000113" , nome: "José Maria Pinto de Figueiredo"               , email: "zemaria@prodam.am.gov.br"                          ).save senha: "_000113"
(Usuario.new nome_usuario: "p000606" , nome: "Regis Alberto Müller da Silva"                , email: "regismuller@prodam.am.gov.br"                      ).save senha: "_000606"
(Usuario.new nome_usuario: "p001128" , nome: "Hirla Maria Fernandes Batista"                , email: "hirla@seplan.am.gov.br"                            ).save senha: "_001128"
(Usuario.new nome_usuario: "p001063" , nome: "Adriana dos Santos Reis Freire"               , email: "adriana@prodam.am.gov.br"                          ).save senha: "_001063"
(Usuario.new nome_usuario: "p001170" , nome: "Claudomiro de Almeida Morais"                 , email: "claudomiro@prosamim.am.gov.br"                     ).save senha: "_001170"
(Usuario.new nome_usuario: "p000022" , nome: "Francisco de Queiroz"                         , email: "queiroz@seplan.am.gov.br"                          ).save senha: "_000022"
(Usuario.new nome_usuario: "p001038" , nome: "Moysés Marcio Nogueira Martins"               , email: "moyses.martins@sefaz.am.gov.br"                    ).save senha: "_001038"
(Usuario.new nome_usuario: "p001208" , nome: "Antão Fagundes Derzi Neto"                    , email: "antao@prodam.am.gov.br"                            ).save senha: "_001208"
(Usuario.new nome_usuario: "p001139" , nome: "Carlos Tullio dos Santos Demasi"              , email: "demasi@prodam.am.gov.br"                           ).save senha: "_001139"
(Usuario.new nome_usuario: "p001217" , nome: "Celziana Miranda Lima"                        , email: "cmiranda@prodam.am.gov.br"                         ).save senha: "_001217"
(Usuario.new nome_usuario: "p000060" , nome: "Maria Thereza Nery Xavier"                    , email: "p000060-noemail@prodam.am.gov.br"                  ).save senha: "_000060"
(Usuario.new nome_usuario: "p001323" , nome: "Jackson José de Freitas Nobre"                , email: "jackson@prodam.am.gov.br"                          ).save senha: "_001323"
(Usuario.new nome_usuario: "p001402" , nome: "Jairo Correa Fernandes"                       , email: "jfernandes@prodam.am.gov.br"                       ).save senha: "_001402"
(Usuario.new nome_usuario: "p001078" , nome: "Marcelo Iannuzzi da Silveira"                 , email: "msilveira@prodam.am.gov.br"                        ).save senha: "_001078"
(Usuario.new nome_usuario: "p000991" , nome: "Vera Luíza Rocha Navarro"                     , email: "vera.luiza@prodam.am.gov.br"                       ).save senha: "_000991"
(Usuario.new nome_usuario: "p001428" , nome: "Fredson Lopes Menezes"                        , email: "fredson@prodam.am.gov.br"                          ).save senha: "_001428"
(Usuario.new nome_usuario: "p001391" , nome: "Glauco Kramer da Silva Santos"                , email: "glauco@prodam.am.gov.br"                           ).save senha: "_001391"
(Usuario.new nome_usuario: "p001129" , nome: "Júlio Bernardino da Silva"                    , email: "jbsilva@prodam.am.gov.br"                          ).save senha: "_001129"
(Usuario.new nome_usuario: "p000312" , nome: "Luíz Carlos Pinto Saraiva"                    , email: "luiz@prodam.am.gov.br"                             ).save senha: "_000312"
(Usuario.new nome_usuario: "p001135" , nome: "Mario da Conceição Fonseca Junior"            , email: "mariocfonseca@prodam.am.gov.br"                    ).save senha: "_001135"
(Usuario.new nome_usuario: "p001037" , nome: "Cláudio Ferreira da Silva"                    , email: "claudio.silva@prodam.am.gov.br"                    ).save senha: "_001037"
(Usuario.new nome_usuario: "p000653" , nome: "Clodoaldo Ferreira dos Santos Junior"         , email: "cfsantos@prodam.am.gov.br"                         ).save senha: "_000653"
(Usuario.new nome_usuario: "p001443" , nome: "Elton Serra Ribeiro Couto"                    , email: "elton.couto@prodam.am.gov.br"                      ).save senha: "_001443"
(Usuario.new nome_usuario: "p000654" , nome: "Evandro Içá Amazonense Aparício dos Santos"   , email: "eica@prodam.am.gov.br"                             ).save senha: "_000654"
(Usuario.new nome_usuario: "p001310" , nome: "Francisco Charles Uchoa de Lima"              , email: "fclima@prodam.am.gov.br"                           ).save senha: "_001310"
(Usuario.new nome_usuario: "p001126" , nome: "Mario Augusto Batista Rocha"                  , email: "mario@prodam.am.gov.br"                            ).save senha: "_001126"
(Usuario.new nome_usuario: "p000613" , nome: "Rozete Roberto Campos"                        , email: "rozete@prodam.am.gov.br"                           ).save senha: "_000613"
(Usuario.new nome_usuario: "p001439" , nome: "Sebastião Francisco da Silva"                 , email: "sebastiao.silva@prodam.am.gov.br"                  ).save senha: "_001439"
(Usuario.new nome_usuario: "p001337" , nome: "Stones da Costa Machado Júnior"               , email: "stones@prodam.am.gov.br"                           ).save senha: "_001337"
(Usuario.new nome_usuario: "p000018" , nome: "José Carlos Torres da Silva Filho"            , email: "jcarlost@prodam.gov.am.br"                         ).save senha: "_000018"
(Usuario.new nome_usuario: "p000354" , nome: "Raimundo Vítor da Silva Neto"                 , email: "rvitor@prodam.am.gov.br"                           ).save senha: "_000354"
(Usuario.new nome_usuario: "p001352" , nome: "Fernanda Ferreira Andrade"                    , email: "fandrade@sefaz.am.gov.br"                          ).save senha: "_001352"
(Usuario.new nome_usuario: "p001051" , nome: "Hallison Vasconcelos Batista"                 , email: "hallison.batista@prodam.am.gov.br"                 ).save senha: "_001051"
(Usuario.new nome_usuario: "p001207" , nome: "José Antonio de Melo Salvador"                , email: "joseantonio@prodam.am.gov.br"                      ).save senha: "_001207"
(Usuario.new nome_usuario: "p001072" , nome: "Amélia de Souza Fernandes"                    , email: "amelia.araujo@prodam.am.gov.br"                    ).save senha: "_001072"
(Usuario.new nome_usuario: "p001427" , nome: "Amaury Magalhães Colares"                     , email: "amaury.colares@prodam.am.gov.br"                   ).save senha: "_001427"
(Usuario.new nome_usuario: "p001421" , nome: "David Teixeira Souza"                         , email: "david@prodam.am.gov.br"                            ).save senha: "_001421"
(Usuario.new nome_usuario: "p000879" , nome: "Emerson Silva da Cruz"                        , email: "emersoncruz@prodam.am.gov.br"                      ).save senha: "_000879"
(Usuario.new nome_usuario: "p000510" , nome: "Tereza D`Ávila da Costa Monteiro"             , email: "davila@prodam.am.gov.br"                           ).save senha: "_000510"
(Usuario.new nome_usuario: "p001200" , nome: "Aliane Oliveira Diniz"                        , email: "alianediniz@prodam.am.gov.br"                      ).save senha: "_001200"
(Usuario.new nome_usuario: "p001202" , nome: "Gemerson Monteiro Maciel"                     , email: "gemerson@prodam.am.gov.br"                         ).save senha: "_001202"
(Usuario.new nome_usuario: "p000418" , nome: "Oto Luiz Gonzaga Mendes"                      , email: "oto@prodam.am.gov.br"                              ).save senha: "_000418"
(Usuario.new nome_usuario: "p001180" , nome: "Priscilla Jeanne Matos de Melo"               , email: "priscilla.melo@prodam.am.gov.br"                   ).save senha: "_001180"
(Usuario.new nome_usuario: "p001249" , nome: "Afonso Fonseca Fernandes"                     , email: "afonso.fonseca@prodam.am.gov.br"                   ).save senha: "_001249"
(Usuario.new nome_usuario: "p000551" , nome: "Deusdedite Borges Dias"                       , email: "deusdedite@prodam.am.gov.br"                       ).save senha: "_000551"
(Usuario.new nome_usuario: "p000431" , nome: "Maria do Perpétuo Socorro Nery de Lima"       , email: "socorro@prodam.am.gov.br"                          ).save senha: "_000431"
(Usuario.new nome_usuario: "p000409" , nome: "Carlos Alberto Amazonas de  Meneses"          , email: "cmenezes@prodam.am.gov.br"                         ).save senha: "_000409"
(Usuario.new nome_usuario: "p000442" , nome: "Célio de Castro Caitete"                      , email: "celio@prodam.am.gov.br"                            ).save senha: "_000442"
(Usuario.new nome_usuario: "p000776" , nome: "Elias Oliveira da Silva"                      , email: "elias@prodam.am.gov.br"                            ).save senha: "_000776"
(Usuario.new nome_usuario: "p000910" , nome: "Júlio César D´Oliveira e Souza"               , email: "jcdos@prodam.am.gov.br"                            ).save senha: "_000910"
(Usuario.new nome_usuario: "p000480" , nome: "Kleider Nonato Montoril Rocha"                , email: "kleider@prodam.am.gov.br"                          ).save senha: "_000480"
(Usuario.new nome_usuario: "p000377" , nome: "Leila Farias Fernandes"                       , email: "leila@prodam.am.gov.br"                            ).save senha: "_000377"
(Usuario.new nome_usuario: "p000569" , nome: "Manoel Roberto Teixeira da Silva"             , email: "manoel.roberto@prodam.am.gov.br"                   ).save senha: "_000569"
(Usuario.new nome_usuario: "p000611" , nome: "Paulo Augusto Praia dos Santos Pereira"       , email: "paulo.pereira@prodam.am.gov.br"                    ).save senha: "_000611"
(Usuario.new nome_usuario: "p000397" , nome: "Paulo Rubem Libertino da Silveira"            , email: "paulo.silveira@prodam.am.gov.br"                   ).save senha: "_000397"
(Usuario.new nome_usuario: "p001198" , nome: "Renato Campelo de Carvalho Filho"             , email: "rcampelo@prodam.am.gov.br"                         ).save senha: "_001198"
(Usuario.new nome_usuario: "p000428" , nome: "Waslany Bittencourt Saraiva"                  , email: "lany@prodam.am.gov.br"                             ).save senha: "_000428"
(Usuario.new nome_usuario: "p001324" , nome: "Adeildo Martins Pereira Junior"               , email: "adeildo@prodam.am.gov.br"                          ).save senha: "_001324"
(Usuario.new nome_usuario: "p001285" , nome: "Anne Caroline Silva Bandeira"                 , email: "anne@prodam.am.gov.br"                             ).save senha: "_001285"
(Usuario.new nome_usuario: "p001153" , nome: "Cleany Fernandes do Carmo Silva"              , email: "cleanyfernandes@prodam.am.gov.br"                  ).save senha: "_001153"
(Usuario.new nome_usuario: "p000988" , nome: "Cristianne Lima Martins"                      , email: "cristianne@prodam.am.gov.br"                       ).save senha: "_000988"
(Usuario.new nome_usuario: "p001201" , nome: "Deiwe Pereira Furtado"                        , email: "deiwe@prodam.am.gov.br"                            ).save senha: "_001201"
(Usuario.new nome_usuario: "p001334" , nome: "Délcio Canuto Coelho Júnior"                  , email: "delcio@prodam.am.gov.br"                           ).save senha: "_001334"
(Usuario.new nome_usuario: "p000453" , nome: "Elsilene Coelho Bastos"                       , email: "elsilene@prodam.am.gov.br"                         ).save senha: "_000453"
(Usuario.new nome_usuario: "p000371" , nome: "Heloisa Maria Souza da Silva"                 , email: "heloisa@prodam.am.gov.br"                          ).save senha: "_000371"
(Usuario.new nome_usuario: "p001273" , nome: "Hiram Lopes Filho"                            , email: "hiram@prodam.am.gov.br"                            ).save senha: "_001273"
(Usuario.new nome_usuario: "p000661" , nome: "Lara Diana da Silva Lopes"                    , email: "lara@prodam.am.gov.br"                             ).save senha: "_000661"
(Usuario.new nome_usuario: "p001298" , nome: "Renato Borges de Souza"                       , email: "renato.borges@prodam.am.gov.br"                    ).save senha: "_001298"
(Usuario.new nome_usuario: "p001321" , nome: "Roseli Jacob"                                 , email: "roselij@prodam.am.gov.br"                          ).save senha: "_001321"
(Usuario.new nome_usuario: "p001437" , nome: "Willian Santos de Albuquerque"                , email: "willian.albuquerque@prodam.am.gov.br"              ).save senha: "_001437"
(Usuario.new nome_usuario: "p001203" , nome: "Emerson Silva de Souza"                       , email: "emerson.souza@prodam.am.gov.br"                    ).save senha: "_001203"
(Usuario.new nome_usuario: "p001440" , nome: "Edisa Santos de Oliveira"                     , email: "edisa@prodam.am.gov.br"                            ).save senha: "_001440"
(Usuario.new nome_usuario: "p000413" , nome: "Izabel Lima Barbosa"                          , email: "ilima@prodam.am.gov.br"                            ).save senha: "_000413"
(Usuario.new nome_usuario: "p001248" , nome: "Paula Tavares Amorim"                         , email: "paula.tavares@prodam.am.gov.br"                    ).save senha: "_001248"
(Usuario.new nome_usuario: "p000560" , nome: "Raimundo Araújo Barbosa Junior"               , email: "rjunior@prodam.am.gov.br"                          ).save senha: "_000560"
(Usuario.new nome_usuario: "p001418" , nome: "Ricardo Albuquerque Neves"                    , email: "ricardo.neves@prodam.am.gov.br"                    ).save senha: "_001418"
(Usuario.new nome_usuario: "p001375" , nome: "Vainer Bastos Munhoz"                         , email: "vainer@prodam.am.gov.br"                           ).save senha: "_001375"
(Usuario.new nome_usuario: "p001175" , nome: "Andrew Stevenson da Silva Siza"               , email: "andrewsiza@tce.am.gov.br"                          ).save senha: "_001175"
(Usuario.new nome_usuario: "p001373" , nome: "Corintho Fernandes de Lima Neto"              , email: "corintho.neto@tce.am.gov.br"                       ).save senha: "_001373"
(Usuario.new nome_usuario: "p001035" , nome: "Fabrício Rogério Cyrino Barbosa"              , email: "fabricio@tce.am.gov.br"                            ).save senha: "_001035"
(Usuario.new nome_usuario: "p001117" , nome: "Glaucio Cezar Alves Hayden Júnior"            , email: "glaucio@tce.am.gov.br"                             ).save senha: "_001117"
(Usuario.new nome_usuario: "p001166" , nome: "Igson Mendes da Silva"                        , email: "igson@tce.am.gov.br"                               ).save senha: "_001166"
(Usuario.new nome_usuario: "p001120" , nome: "Lincoln Andrade Santos"                       , email: "lincoln@tce.am.gov.br"                             ).save senha: "_001120"
(Usuario.new nome_usuario: "p001434" , nome: "Endel Batista Passos"                         , email: "endel@prodam.am.gov.br"                            ).save senha: "_001434"
(Usuario.new nome_usuario: "p000553" , nome: "Erly Pereira Cezar"                           , email: "erly@prodam.am.gov.br"                             ).save senha: "_000553"
(Usuario.new nome_usuario: "p000300" , nome: "Maria Cristina Braga Trigueiro"               , email: "cristina@prodam.am.gov.br"                         ).save senha: "_000300"
(Usuario.new nome_usuario: "p000968" , nome: "Francisco Ricardo Pereira Fernandes"          , email: "fricardo@prodam.am.gov.br"                         ).save senha: "_000968"
(Usuario.new nome_usuario: "p001374" , nome: "Hemanuel  Quirino Matozinho e Silva"          , email: "hemanuel.silva@prodam.am.gov.br"                   ).save senha: "_001374"
(Usuario.new nome_usuario: "p001342" , nome: "Ismael Benigno Neto"                          , email: "ismael@prodam.am.gov.br"                           ).save senha: "_001342"
(Usuario.new nome_usuario: "p000461" , nome: "José Casimiro de Araújo"                      , email: "casimiro@prodam.am.gov.br"                         ).save senha: "_000461"
(Usuario.new nome_usuario: "p000147" , nome: "Juracilda Maria Mota Henriques"               , email: "p000147-noemail@prodam.am.gov.br"                  ).save senha: "_000147"
(Usuario.new nome_usuario: "p000642" , nome: "Roselene Lima Nascimento"                     , email: "rosele@prodam.am.gov.br"                           ).save senha: "_000642"
(Usuario.new nome_usuario: "p000451" , nome: "Cheila Sabóia de Souza"                       , email: "cheila@prodam.am.gov.br"                           ).save senha: "_000451"
(Usuario.new nome_usuario: "p000662" , nome: "Eduardo Alexandre Palmeira Vieira"            , email: "eduardovieira@prodam.am.gov.br"                    ).save senha: "_000662"
(Usuario.new nome_usuario: "p000555" , nome: "Haddock Jânio Mendes Petillo"                 , email: "haddock@prodam.am.gov.br"                          ).save senha: "_000555"
(Usuario.new nome_usuario: "p001429" , nome: "Jéssica Monteiro da Silva e Silva"            , email: "jessica.monteiro@prodam.am.gov.br"                 ).save senha: "_001429"
(Usuario.new nome_usuario: "p000508" , nome: "Frank Jefferson de Farias Cardoso"            , email: "frankjef@prodam.am.gov.br"                         ).save senha: "_000508"
(Usuario.new nome_usuario: "p001369" , nome: "Danielle Costa de Souza Simas"                , email: "danielle.souza@prodam.am.gov.br"                   ).save senha: "_001369"
(Usuario.new nome_usuario: "p000524" , nome: "Claudio Feliciano Feitosa Valente"            , email: "claudio@prodam.am.gov.br"                          ).save senha: "_000524"
(Usuario.new nome_usuario: "p000235" , nome: "Adolfo Braga Trigueiro"                       , email: "adolfo@prodam.am.gov.br"                           ).save senha: "_000235"
(Usuario.new nome_usuario: "p000167" , nome: "Antonio César Vieira de Lima"                 , email: "cesar@prodam.am.gov.br"                            ).save senha: "_000167"
(Usuario.new nome_usuario: "p000436" , nome: "Eliana das Graças Ribeiro da Mota"            , email: "elianamota@prodam.am.gov.br"                       ).save senha: "_000436"
(Usuario.new nome_usuario: "p001029" , nome: "Salim Silva David"                            , email: "salim@prodam.am.gov.br"                            ).save senha: "_001029"
(Usuario.new nome_usuario: "p000829" , nome: "Claudemir Ivan de Lima Gomes"                 , email: "ivan@prodam.am.gov.br"                             ).save senha: "_000829"
(Usuario.new nome_usuario: "p000986" , nome: "Lelson Lopes Nascimento"                      , email: "lelson@prodam.am.gov.br"                           ).save senha: "_000986"
(Usuario.new nome_usuario: "p001211" , nome: "Alan Valdberto Laranjeira da Silva"           , email: "alan.silva@prodam.am.gov.br"                       ).save senha: "_001211"
(Usuario.new nome_usuario: "p001156" , nome: "Domingos Manoel Oran Barros Coelho Júnior"    , email: "domingos@prodam.am.gov.br"                         ).save senha: "_001156"
(Usuario.new nome_usuario: "p001357" , nome: "Humberto Tomais da Silva"                     , email: "humberto@prodam.am.gov.br"                         ).save senha: "_001357"
(Usuario.new nome_usuario: "p001394" , nome: "Polyanna Wenze Sousa da Silva"                , email: "polyanna.silva@prodam.am.gov.br"                   ).save senha: "_001394"
(Usuario.new nome_usuario: "p001372" , nome: "Dennys Lyo Silva dos Santos"                  , email: "dennys@sefaz.am.gov.br"                            ).save senha: "_001372"
(Usuario.new nome_usuario: "p001309" , nome: "André Tavares de Brito"                       , email: "andre.tavares@prodam.am.gov.br"                    ).save senha: "_001309"
(Usuario.new nome_usuario: "p001083" , nome: "Danubia Ramos Lustosa"                        , email: "danubia@prodam.am.gov.br"                          ).save senha: "_001083"
(Usuario.new nome_usuario: "p001003" , nome: "Eliane Frota Sampaio"                         , email: "elianefrota@prodam.am.gov.br"                      ).save senha: "_001003"
(Usuario.new nome_usuario: "p001251" , nome: "Fábio Paes Barreto de Carvalho"               , email: "fabio.barreto@prodam.am.gov.br"                    ).save senha: "_001251"
(Usuario.new nome_usuario: "p001144" , nome: "Gilson de Sena da Silva"                      , email: "gilson@prodam.am.gov.br"                           ).save senha: "_001144"
(Usuario.new nome_usuario: "p001306" , nome: "Gisely Rebouças Lima"                         , email: "gisely@prodam.am.gov.br"                           ).save senha: "_001306"
(Usuario.new nome_usuario: "p001307" , nome: "Josenei Campelo Gomes"                        , email: "josenei@prodam.am.gov.br"                          ).save senha: "_001307"
(Usuario.new nome_usuario: "p001385" , nome: "Luciano da Costa Pinto"                       , email: "lcosta@prodam.am.gov.br"                           ).save senha: "_001385"
(Usuario.new nome_usuario: "p001068" , nome: "Marcelo Ramos Pereira"                        , email: "mpereira@prodam.am.gov.br"                         ).save senha: "_001068"
(Usuario.new nome_usuario: "p000319" , nome: "Paulo Roberto Guerreiro Saraiva"              , email: "psaraiva@prodam.am.gov.br"                         ).save senha: "_000319"
(Usuario.new nome_usuario: "p000942" , nome: "José Geraldo Ferreira Gomes"                  , email: "jgeraldo@sefaz.am.gov.br"                          ).save senha: "_000942"
(Usuario.new nome_usuario: "p000981" , nome: "Amaury Cézar Menezes Cavalcante"              , email: "amaury@prodam.am.gov.br"                           ).save senha: "_000981"
(Usuario.new nome_usuario: "p001099" , nome: "Alexsandro Moyses Oliveira de Meneses"        , email: "alex.moyses@prodam.am.gov.br"                      ).save senha: "_001099"
(Usuario.new nome_usuario: "p000971" , nome: "Aquiles Freitas Ventilari"                    , email: "aquiles@prodam.am.gov.br"                          ).save senha: "_000971"
(Usuario.new nome_usuario: "p001032" , nome: "Edberg Medeiros Soares"                       , email: "edberg@casacivil.am.gov.br"                        ).save senha: "_001032"
(Usuario.new nome_usuario: "p000626" , nome: "José Gilson de Oliveira"                      , email: "jgilson@sefaz.am.gov.br"                           ).save senha: "_000626"
(Usuario.new nome_usuario: "p000605" , nome: "Gilson dos Santos de Oliveira"                , email: "gilson.santos@prodam.am.gov.br"                    ).save senha: "_000605"
(Usuario.new nome_usuario: "p000732" , nome: "Manoel Cardoso Serra"                         , email: "manoel.cardoso@prodam.am.gov.br"                   ).save senha: "_000732"
(Usuario.new nome_usuario: "p000203" , nome: "Ana Maria da Gama"                            , email: "agama@prodam.am.gov.br"                            ).save senha: "_000203"
(Usuario.new nome_usuario: "p001344" , nome: "Leomax Paulino de Azevedo"                    , email: "leomax@prodam.am.gov.br"                           ).save senha: "_001344"
(Usuario.new nome_usuario: "p000582" , nome: "Regina Célia Lira Benayon"                    , email: "regina.celia@prodam.am.gov.br"                     ).save senha: "_000582"
(Usuario.new nome_usuario: "p000538" , nome: "Josemar Cavalcante de Lima Lopes"             , email: "josemar@prodam.am.gov.br"                          ).save senha: "_000538"
(Usuario.new nome_usuario: "p001105" , nome: "Paulo César  Moreira de Souza"                , email: "pcesar@prodam.am.gov.br"                           ).save senha: "_001105"
(Usuario.new nome_usuario: "p001415" , nome: "Alberto Correia Lima Neto"                    , email: "alberto.neto@prodam.am.gov.br"                     ).save senha: "_001415"
(Usuario.new nome_usuario: "p001416" , nome: "Daniel do Nascimento"                         , email: "daniel.nascimento@prodam.am.gov.br"                ).save senha: "_001416"
(Usuario.new nome_usuario: "p001420" , nome: "Edgard Rafael Veiga da Costa"                 , email: "edgard.costa@prodam.am.gov.br"                     ).save senha: "_001420"
(Usuario.new nome_usuario: "p000738" , nome: "Fábio Lima Ramos"                             , email: "fabiolimaRamos@prodam.am.gov.br"                   ).save senha: "_000738"
(Usuario.new nome_usuario: "p000638" , nome: "Maria Stela da Silva Bastos"                  , email: "mstela@prodam.am.gov.br"                           ).save senha: "_000638"
(Usuario.new nome_usuario: "p001349" , nome: "Quézia Cristina Cantuário de Andrade"         , email: "quezia@prodam.am.gov.br"                           ).save senha: "_001349"
(Usuario.new nome_usuario: "p000424" , nome: "Alcineide Silva de Souza"                     , email: "alcineide@prodam.am.gov.br"                        ).save senha: "_000424"
(Usuario.new nome_usuario: "p001361" , nome: "Carlos Alberto Costa Souza"                   , email: "calberto@prodam.am.gov.br"                         ).save senha: "_001361"
(Usuario.new nome_usuario: "p001351" , nome: "Darlisson Luis Bezerra Vasconcelos"           , email: "darlisson@prodam.am.gov.br"                        ).save senha: "_001351"
(Usuario.new nome_usuario: "p001422" , nome: "Marcelo Anderson Queiroz Borges de Oliveira"  , email: "Marcelo.oliveira@prodam.am.gov.br"                 ).save senha: "_001422"
(Usuario.new nome_usuario: "p001419" , nome: "Marcos Verissimo Santos de Oliveira"          , email: "marcos.oliveira@prodam.am.gov.br"                  ).save senha: "_001419"
(Usuario.new nome_usuario: "p001356" , nome: "Anderson Miranda Viana"                       , email: "amiranda@prodam.am.gov.am"                         ).save senha: "_001356"
(Usuario.new nome_usuario: "p001294" , nome: "Nuno Sanches Silva da Rosa"                   , email: "nuno@prodam.am.gov.br"                             ).save senha: "_001294"
(Usuario.new nome_usuario: "p000391" , nome: "Elselly Coêlho Bastos"                        , email: "elselly@prodam.gov.am.br"                          ).save senha: "_000391"
(Usuario.new nome_usuario: "p000775" , nome: "Guaraci Nogueira Damasceno"                   , email: "p000775-noemail@prodam.am.gov.br"                  ).save senha: "_000775"
(Usuario.new nome_usuario: "p000935" , nome: "Guaracy Barroso Monteiro"                     , email: "guaracy@prodam.am.gov.br"                          ).save senha: "_000935"
(Usuario.new nome_usuario: "p000857" , nome: "Hélio Pinheiro da Silva"                      , email: "p000857-noemail@prodam.am.gov.br"                  ).save senha: "_000857"
(Usuario.new nome_usuario: "p000350" , nome: "Lúcia Maria dos Santos Proença"               , email: "p000350-noemail@prodam.am.gov.br"                  ).save senha: "_000350"
(Usuario.new nome_usuario: "p000500" , nome: "Luiz Carlos Bezerra"                          , email: "p000500-noemail@prodam.am.gov.br"                  ).save senha: "_000500"
(Usuario.new nome_usuario: "p000534" , nome: "Maria Ana Angélica Cordeiro Ribeiro"          , email: "p000534-noemail@prodam.am.gov.br"                  ).save senha: "_000534"
(Usuario.new nome_usuario: "p000909" , nome: "Maria Nilza de Souza"                         , email: "p000909-noemail@prodam.am.gov.br"                  ).save senha: "_000909"
(Usuario.new nome_usuario: "p000501" , nome: "Ivanize Maria de Lima Vieira"                 , email: "ivanize@prodam.am.gov.br"                          ).save senha: "_000501"
(Usuario.new nome_usuario: "p000366" , nome: "Kleper Osório Nunes"                          , email: "kleper@prodam.am.gov.br"                           ).save senha: "_000366"
(Usuario.new nome_usuario: "p000565" , nome: "Liliana Campos dos Santos"                    , email: "liliana@prodam.am.gov.br"                          ).save senha: "_000565"
(Usuario.new nome_usuario: "p000254" , nome: "Maria de Belém Sozinho Laborda"               , email: "mabel@prodam.am.gov.br"                            ).save senha: "_000254"
(Usuario.new nome_usuario: "p000106" , nome: "Norma Bastos da Silva Almeida"                , email: "norma@prodam.am.gov.br"                            ).save senha: "_000106"
(Usuario.new nome_usuario: "p000581" , nome: "Sérgio Rodrigues da Silva"                    , email: "sergio@prodam.am.gov.br"                           ).save senha: "_000581"
(Usuario.new nome_usuario: "p000402" , nome: "Wilson Oliveira de Souza Filho"               , email: "wilson@prodam.am.gov.br"                           ).save senha: "_000402"
(Usuario.new nome_usuario: "p000984" , nome: "Anderson Silva do Nascimento"                 , email: "anderson@prodam.am.gov.br"                         ).save senha: "_000984"
(Usuario.new nome_usuario: "p001325" , nome: "Fábio Alessandro de Araújo Antonaccio"        , email: "fabio.antonaccio@prodam.am.gov.br"                 ).save senha: "_001325"
(Usuario.new nome_usuario: "p001396" , nome: "Jean Carlo Sena"                              , email: "jsena@prodam.am.gov.br"                            ).save senha: "_001396"
(Usuario.new nome_usuario: "p001398" , nome: "Pedro Benevides Lima de Alencar"              , email: "pbenevides@prodam.am.gov.br"                       ).save senha: "_001398"
(Usuario.new nome_usuario: "p001399" , nome: "Ralph Nogueira Haddad"                        , email: "ralph@prodam.am.gov.br"                            ).save senha: "_001399"
(Usuario.new nome_usuario: "p001287" , nome: "Roger Tadeu Muller da Silva"                  , email: "roger@prodam.am.gov.br"                            ).save senha: "_001287"
(Usuario.new nome_usuario: "p001322" , nome: "Bruno Mendes"                                 , email: "bruno.mendes@prodam.am.gov.br"                     ).save senha: "_001322"
(Usuario.new nome_usuario: "p001098" , nome: "Eduardo Lima Costa"                           , email: "eduardocosta@prodam.am.gov.br"                     ).save senha: "_001098"
(Usuario.new nome_usuario: "p001283" , nome: "Felipe Diôgo de Souza Pereira"                , email: "felipe@prodamnet.com.br"                           ).save senha: "_001283"
(Usuario.new nome_usuario: "p001303" , nome: "Marcos Antonio da Silva Gomes"                , email: "marcos.gomes@prodam.am.gov.br"                     ).save senha: "_001303"
(Usuario.new nome_usuario: "p001163" , nome: "Mauro Michel da Cruz Gonçalves"               , email: "mauro@prodam.am.gov.br"                            ).save senha: "_001163"
(Usuario.new nome_usuario: "p001209" , nome: "Raphael Maquiné Marinho"                      , email: "raphael.maquine@prodam.am.gov.br"                  ).save senha: "_001209"
(Usuario.new nome_usuario: "p001269" , nome: "Romeu Franzoia Junior"                        , email: "romeu@prodam.am.gov.br"                            ).save senha: "_001269"
(Usuario.new nome_usuario: "p001194" , nome: "Thulio Silva de Queiroz"                      , email: "thulio@prodam.am.gov.br"                           ).save senha: "_001194"
(Usuario.new nome_usuario: "p001376" , nome: "Akelaus Nascimento Silva"                     , email: "akelaus@prodam.am.gov.br"                          ).save senha: "_001376"
(Usuario.new nome_usuario: "p001141" , nome: "Daniel Felipe Dias"                           , email: "daniel.dias@prodam.am.gov.br"                      ).save senha: "_001141"
(Usuario.new nome_usuario: "p000822" , nome: "José Carlos Azevedo Evangelista"              , email: "carlos@prodam.am.gov.br"                           ).save senha: "_000822"
(Usuario.new nome_usuario: "p001075" , nome: "José Jurany Guimarães da Silva Junior"        , email: "jurany@prodam.am.gov.br"                           ).save senha: "_001075"
(Usuario.new nome_usuario: "p001425" , nome: "Lammunier Lima dos Santos"                    , email: "lammunier@prodam.am.gov.br"                        ).save senha: "_001425"
(Usuario.new nome_usuario: "p000688" , nome: "Maria do Perpétuo Socorro de Oliveira Passos" , email: "socorropassos@prodam.am.gov.br"                    ).save senha: "_000688"
(Usuario.new nome_usuario: "p001046" , nome: "Michael da Silva Marinho"                     , email: "michael@prodam.am.gov.br"                          ).save senha: "_001046"
(Usuario.new nome_usuario: "p001343" , nome: "Paulo Bruno Barbosa de Melo"                  , email: "paulo.bruno@prodam.am.gov.br"                      ).save senha: "_001343"
(Usuario.new nome_usuario: "p000700" , nome: "Renato Pereira de Lima"                       , email: "renato@prodamnet.com.br"                           ).save senha: "_000700"
(Usuario.new nome_usuario: "p001243" , nome: "Julio Cesar Ferreira Ribeiro"                 , email: "julio.ribeiro@prodam.am.gov.br"                    ).save senha: "_001243"
(Usuario.new nome_usuario: "p001304" , nome: "Rondinelli Vasconcelos Holanda"               , email: "rondinelli@prodam.am.gov.br"                       ).save senha: "_001304"
(Usuario.new nome_usuario: "p001412" , nome: "Cleane Vidal Teixeira"                        , email: "cleane.teixeira@prodam.am.gov.br"                  ).save senha: "_001412"
(Usuario.new nome_usuario: "p000280" , nome: "Elaine Tereza Pessoa da Silva"                , email: "elaine@prodam.am.gov.br"                           ).save senha: "_000280"
(Usuario.new nome_usuario: "p000339" , nome: "Maria de Fátima  Bezerra de Oliveira"         , email: "fbezerra@prodam.am.gov.br"                         ).save senha: "_000339"
(Usuario.new nome_usuario: "p000289" , nome: "Rosângela Alencar dos Santos"                 , email: "rosangela@prodam.am.gov.br"                        ).save senha: "_000289"
(Usuario.new nome_usuario: "p001189" , nome: "Alysson Campos Ramos"                         , email: "alyssoncampos@prodam.am.gov.br"                    ).save senha: "_001189"
(Usuario.new nome_usuario: "p001215" , nome: "Cesar Rômulo dos Santos Pereira"              , email: "cromulo@prodam.am.gov.br"                          ).save senha: "_001215"
(Usuario.new nome_usuario: "p001061" , nome: "Cristiano Crisnaya dos Santos Malcher"        , email: "cristianomalcher@prodam.am.gov.br"                 ).save senha: "_001061"
(Usuario.new nome_usuario: "p001358" , nome: "Fabio Amoedo Junior"                          , email: "fabio.amoedo@seduc.am.gov.br"                      ).save senha: "_001358"
(Usuario.new nome_usuario: "p000962" , nome: "João Guilherme de Moraes Silva"               , email: "guilherme@prodam.am.gov.br"                        ).save senha: "_000962"
(Usuario.new nome_usuario: "p000978" , nome: "Marcio Rogério da Silva Belmont"              , email: "belmont@prodam.am.gov.br"                          ).save senha: "_000978"
(Usuario.new nome_usuario: "p001395" , nome: "Sávio dos Santos Nascimento"                  , email: "ssantos@prodam.am.gov.br"                          ).save senha: "_001395"
(Usuario.new nome_usuario: "p000669" , nome: "Vivaldo Dias de Lima"                         , email: "vlima@prodam.am.gov.br"                            ).save senha: "_000669"
(Usuario.new nome_usuario: "p001256" , nome: "Helca Karen Puget de Oliveira"                , email: "helca@prodam.am.gov.br"                            ).save senha: "_001256"
(Usuario.new nome_usuario: "p000441" , nome: "Ester Sales da Costa Queiroz"                 , email: "ester@prodam.am.gov.br"                            ).save senha: "_000441"
(Usuario.new nome_usuario: "p000698" , nome: "Francisco de Nazaré Nogueira"                 , email: "fnazare@prodam.am.gov.br"                          ).save senha: "_000698"
(Usuario.new nome_usuario: "p000864" , nome: "Jefferson Menezes do Carmo"                   , email: "jmenezes@prodam.am.gov.br"                         ).save senha: "_000864"
(Usuario.new nome_usuario: "p001124" , nome: "Luany Bittencourt Saraiva de Melo"            , email: "luany@prodam.am.gov.br"                            ).save senha: "_001124"
(Usuario.new nome_usuario: "p000140" , nome: "Marlene dos Santos Teixeira de Araújo"        , email: "marlene@prodam.am.gov.br"                          ).save senha: "_000140"
(Usuario.new nome_usuario: "p001226" , nome: "Abel Gomes da Silva Neto"                     , email: "abel.neto@sefaz.am.gov.br"                         ).save senha: "_001226"
(Usuario.new nome_usuario: "p001363" , nome: "Adriano Gomes de Souza"                       , email: "a.gomes@sefaz.am.gov.br"                           ).save senha: "_001363"
(Usuario.new nome_usuario: "p001382" , nome: "André de Farias Paes Landim"                  , email: "alandim@sefaz.am.gov.br"                           ).save senha: "_001382"
(Usuario.new nome_usuario: "p001441" , nome: "André Ricardo Melo Araújo"                    , email: "a.araujo@sefaz.am.gov.br"                          ).save senha: "_001441"
(Usuario.new nome_usuario: "p000729" , nome: "Antonio Luiz de Freitas Pauxis"               , email: "pauxis@sefaz.am.gov.br"                            ).save senha: "_000729"
(Usuario.new nome_usuario: "p001299" , nome: "Bruno dos Santos Ferreira"                    , email: "bruno@sefaz.am.gov.br"                             ).save senha: "_001299"
(Usuario.new nome_usuario: "p001065" , nome: "Carlos Souza dos Santos"                      , email: "csouza@sefaz.am.gov.br"                            ).save senha: "_001065"
(Usuario.new nome_usuario: "p000226" , nome: "Célia da Costa Pinto"                         , email: "cpinto@sefaz.am.gov.br"                            ).save senha: "_000226"
(Usuario.new nome_usuario: "p000610" , nome: "César Augusto Rodrigues"                      , email: "caugusto@sefaz.am.gov.br"                          ).save senha: "_000610"
(Usuario.new nome_usuario: "p001220" , nome: "Cinthia Silva da Cruz"                        , email: "cinthia.cruz@sefaz.am.gov.br"                      ).save senha: "_001220"
(Usuario.new nome_usuario: "p001317" , nome: "Clarice de Souza Santos"                      , email: "cmesquita@sefaz.am.gov.br"                         ).save senha: "_001317"
(Usuario.new nome_usuario: "p001100" , nome: "Claudio Batista de Lima"                      , email: "cblima@prodam.am.gov.br"                           ).save senha: "_001100"
(Usuario.new nome_usuario: "p001236" , nome: "Davi Costa Pinto"                             , email: "davi.costa@prodam.am.gov.br"                       ).save senha: "_001236"
(Usuario.new nome_usuario: "p001312" , nome: "Diego Melo Cruz"                              , email: "dcruz@sefaz.am.gov.br"                             ).save senha: "_001312"
(Usuario.new nome_usuario: "p001171" , nome: "Edécio Matias Neto"                           , email: "eneto@sefaz.am.gov.br"                             ).save senha: "_001171"
(Usuario.new nome_usuario: "p000885" , nome: "Ediberto Oliveira da Silva"                   , email: "eoliveira@sefaz.am.gov.br"                         ).save senha: "_000885"
(Usuario.new nome_usuario: "p001354" , nome: "Edson Régis da Silva Filho"                   , email: "efilho@sefaz.am.gov.br"                            ).save senha: "_001354"
(Usuario.new nome_usuario: "p001111" , nome: "Eduardo Jorge Aucar Seffair Filho"            , email: "eduardo.seffair@sefaz.am.gov.br"                   ).save senha: "_001111"
(Usuario.new nome_usuario: "p001182" , nome: "Eduardo Távora de Albuquerque Taveira"        , email: "etaveira@sefaz.am.gov.br"                          ).save senha: "_001182"
(Usuario.new nome_usuario: "p001050" , nome: "Elderson Jammer Lima da Silva"                , email: "esilva@sefaz.am.gov.br"                            ).save senha: "_001050"
(Usuario.new nome_usuario: "p001224" , nome: "Francisco Eder da Silva Pereira"              , email: "fceder@sefaz.am.gov.br"                            ).save senha: "_001224"
(Usuario.new nome_usuario: "p000587" , nome: "Francisco Elzenir Domingos Gomes"             , email: "felzenir@sefaz.am.gov.br"                          ).save senha: "_000587"
(Usuario.new nome_usuario: "p000828" , nome: "Gerson Luiz Martins dos Santos"               , email: "gsantos@sefaz.amgov.br"                            ).save senha: "_000828"
(Usuario.new nome_usuario: "p001033" , nome: "Jake Dôglas Coêlho da Rocha"                  , email: "jake.rocha@sefaz.am.gov.br"                        ).save senha: "_001033"
(Usuario.new nome_usuario: "p001113" , nome: "João Batista Pereira de Carvalho Júnior"      , email: "joaobatista@sefaz.am.gov.br"                       ).save senha: "_001113"
(Usuario.new nome_usuario: "p001081" , nome: "José Rodrigo Orestes de Sousa"                , email: "rsouza@sefaz.am.gov.br"                            ).save senha: "_001081"
(Usuario.new nome_usuario: "p001284" , nome: "Julimar Rian Siqueira da Rocha"               , email: "julimar@prodam.am.gov.br"                          ).save senha: "_001284"
(Usuario.new nome_usuario: "p001371" , nome: "Luciano Aragão de Souza"                      , email: "luciano.aragao@prodam.am.gov.br"                   ).save senha: "_001371"
(Usuario.new nome_usuario: "p000703" , nome: "Luso Rodrigues Bandeira Filho"                , email: "lusobandeira@sefaz.am.gov.br"                      ).save senha: "_000703"
(Usuario.new nome_usuario: "p001368" , nome: "Maisa Vidal Teixeira"                         , email: "mvidal@sefaz.am.gov.br"                            ).save senha: "_001368"
(Usuario.new nome_usuario: "p001384" , nome: "Marcelle Cristina Gonçalves Costa"            , email: "mgcosta@sefaz.am.gov.br"                           ).save senha: "_001384"
(Usuario.new nome_usuario: "p001442" , nome: "Marcos Felipe Paes Pessôa"                    , email: "m.pessoa@sefaz.am.gov.br"                          ).save senha: "_001442"
(Usuario.new nome_usuario: "p000199" , nome: "Maria Paula Pertote de Figueiredo"            , email: "p000199-noemail@sefaz.am.gov.br"                   ).save senha: "_000199"
(Usuario.new nome_usuario: "p001195" , nome: "Mauro Cesar Silva dos Santos"                 , email: "mauro.cesar@prodam.am.gov.br"                      ).save senha: "_001195"
(Usuario.new nome_usuario: "p000523" , nome: "Moacir Silva de Melo"                         , email: "mmelo@sefaz.am.gov.br"                             ).save senha: "_000523"
(Usuario.new nome_usuario: "p001360" , nome: "Nelson Grana de Lima"                         , email: "ngrana@sefaz.am.gov.br"                            ).save senha: "_001360"
(Usuario.new nome_usuario: "p001355" , nome: "Osman Seixas da Penha Júnior"                 , email: "openha@sefaz.am.gov.br"                            ).save senha: "_001355"
(Usuario.new nome_usuario: "p001438" , nome: "Ovídio Lima Nunes dos Santos"                 , email: "o.santos@sefaz.am.gov.br"                          ).save senha: "_001438"
(Usuario.new nome_usuario: "p001040" , nome: "Pedro Daniel da Costa Moda Junior"            , email: "pjunior@sefaz.am.gov.br"                           ).save senha: "_001040"
(Usuario.new nome_usuario: "p001266" , nome: "Ramayana Assunção Menezes"                    , email: "ramayana@sefaz.am.gov.br"                          ).save senha: "_001266"
(Usuario.new nome_usuario: "p001316" , nome: "Ulisses Ricardo de Souza Silva"               , email: "urssilva@sefaz.am.gov.br"                          ).save senha: "_001316"
(Usuario.new nome_usuario: "p001367" , nome: "William Freitas Albuquerque"                  , email: "walbuquerque@sefaz.am.gov.br"                      ).save senha: "_001367"
(Usuario.new nome_usuario: "p001305" , nome: "Wilson Dias da Rocha Neto"                    , email: "wrocha@sefaz.am.gov.br"                            ).save senha: "_001305"
(Usuario.new nome_usuario: "p001328" , nome: "Wolfgang Marcos de Souza Joilton"             , email: "wolfgang@prodam.am.gov.br"                         ).save senha: "_001328"
(Usuario.new nome_usuario: "p001047" , nome: "Edson de Lima Matias Junior"                  , email: "edsonmatiasjr@prodam.am.gov.br"                    ).save senha: "_001047"
(Usuario.new nome_usuario: "p001290" , nome: "Elailson Vieira Figueiredo"                   , email: "elailson@prodam.am.gov.br"                         ).save senha: "_001290"
(Usuario.new nome_usuario: "p001034" , nome: "Luiz Rodrigues Martins Júnior"                , email: "luizrodrigues@prodam.am.gov.br"                    ).save senha: "_001034"
(Usuario.new nome_usuario: "p001196" , nome: "Tiago Rocha da Costa"                         , email: "tiago@prodam.am.gov.br"                            ).save senha: "_001196"
(Usuario.new nome_usuario: "p000016" , nome: "Jair Alves dos Santos"                        , email: "jair@prodam.am.gov.br"                             ).save senha: "_000016"
(Usuario.new nome_usuario: "p000590" , nome: "Joaquim de Moraes Barbosa"                    , email: "joaquim@prodam.am.gov.br"                          ).save senha: "_000590"
(Usuario.new nome_usuario: "p000929" , nome: "Maria do Carmo Moreira Lobato"                , email: "mcarmo@prodam.am.gov.br"                           ).save senha: "_000929"
(Usuario.new nome_usuario: "p001199" , nome: "Salomão Ferreira Lima Neto"                   , email: "salomao@prodam.am.gov.br"                          ).save senha: "_001199"
(Usuario.new nome_usuario: "p000225" , nome: "Vera Lúcia Ferreira da Costa"                 , email: "veralucia@prodam.am.gov.br"                        ).save senha: "_000225"
(Usuario.new nome_usuario: "p001054" , nome: "Anderson Tavares Ferreira"                    , email: "anderson.ferreira@prodam.am.gov.br"                ).save senha: "_001054"
(Usuario.new nome_usuario: "p001218" , nome: "Daniel da Silva Nunes"                        , email: "daniel.silva@prodam.am.gov.br"                     ).save senha: "_001218"
(Usuario.new nome_usuario: "p001405" , nome: "Robson Noriaki Yamada"                        , email: "robson.yamada@prodam.am.gov.br"                    ).save senha: "_001405"
(Usuario.new nome_usuario: "p001295" , nome: "Rodrigo Francisco Menezes"                    , email: "rgrando@prodam.am.gov.br"                          ).save senha: "_001295"
(Usuario.new nome_usuario: "p001400" , nome: "Ulysses Silva de Araújo"                      , email: "ulysses@prodam.am.gov.br"                          ).save senha: "_001400"
(Usuario.new nome_usuario: "p001167" , nome: "Alexandre Franciscani Ferreira"               , email: "franciscani@prodam.am.gov.br"                      ).save senha: "_001167"
(Usuario.new nome_usuario: "p001176" , nome: "Gustavo Simonetti Bomfin"                     , email: "gustavo.simonetti@prodam.am.gov.br"                ).save senha: "_001176"
(Usuario.new nome_usuario: "p000975" , nome: "Lilian Gibson Santos"                         , email: "lilian@prodam.am.gov.br"                           ).save senha: "_000975"
(Usuario.new nome_usuario: "p001077" , nome: "Luiz Augusto Neves Andrade Filho"             , email: "luizaugusto@prodam.am.gov.br"                      ).save senha: "_001077"
(Usuario.new nome_usuario: "p001165" , nome: "André Ricardo Lopes Ferreira"                 , email: "andrericardo@prodam.am.gov.br"                     ).save senha: "_001165"
(Usuario.new nome_usuario: "p001432" , nome: "Caio Flávio Souza de Sena"                    , email: "caioflavio@prodam.am.gov.br"                       ).save senha: "_001432"
(Usuario.new nome_usuario: "p001233" , nome: "Carlos Eduardo Cândido Maia"                  , email: "eduardo@prodam.am.gov.br"                          ).save senha: "_001233"
(Usuario.new nome_usuario: "p001386" , nome: "César Heraldo Lefemir Delgado Junior"         , email: "cesar.heraldo@prodam.am.gov.br"                    ).save senha: "_001386"
(Usuario.new nome_usuario: "p001193" , nome: "Danyson Menezes de Paula"                     , email: "danysonmp@prodam.am.gov.br"                        ).save senha: "_001193"
(Usuario.new nome_usuario: "p001159" , nome: "Francisco Dieles Magalhães de Brito"          , email: "dieles@prodam.am.gov.br"                           ).save senha: "_001159"
(Usuario.new nome_usuario: "p001234" , nome: "Geison Santos do Nascimento"                  , email: "geison@prodam.am.gov.br"                           ).save senha: "_001234"
(Usuario.new nome_usuario: "p001241" , nome: "Gerson da Costa Batista"                      , email: "gerson.costa@prodam.am.gov.br"                     ).save senha: "_001241"
(Usuario.new nome_usuario: "p001276" , nome: "José Silas Barros Brandão Junior"             , email: "silas@prodam.am.gov.br"                            ).save senha: "_001276"
(Usuario.new nome_usuario: "p001431" , nome: "Juliane dos Santos Silva"                     , email: "juliane@prodam.am.gov.br"                          ).save senha: "_001431"
(Usuario.new nome_usuario: "p001401" , nome: "Juscecley Melo da Silva"                      , email: "jmelo@prodam.am.gov.br"                            ).save senha: "_001401"
(Usuario.new nome_usuario: "p001160" , nome: "Katiane Gomes Cavalcante"                     , email: "katigomes@prodam.am.gov.br"                        ).save senha: "_001160"
(Usuario.new nome_usuario: "p001270" , nome: "Paulo Saimon Ramos"                           , email: "paulo.simon@prodamnet.com.br"                      ).save senha: "_001270"
(Usuario.new nome_usuario: "p001267" , nome: "Renan do Carmo Reis"                          , email: "renan.carmo@prodamnet.com.br"                      ).save senha: "_001267"
(Usuario.new nome_usuario: "p001389" , nome: "Rodolfo do Nascimento Azevedo"                , email: "rodolfo@prodam.am.gov.br"                          ).save senha: "_001389"
(Usuario.new nome_usuario: "p001280" , nome: "Rodrigo de Oliveira Santos"                   , email: "rodrigo.santos@prodam.am.gov.br"                   ).save senha: "_001280"
(Usuario.new nome_usuario: "p001390" , nome: "Ronei Macedo Gualberto"                       , email: "ronei@prodam.am.gov.br"                            ).save senha: "_001390"
(Usuario.new nome_usuario: "p001245" , nome: "Valéria Lobato dos Santos"                    , email: "valeria.lobato@prodam.am.gov.br"                   ).save senha: "_001245"
(Usuario.new nome_usuario: "p001329" , nome: "Waldecleber Oliveira Gonçalves"               , email: "waldecleber@prodam.am.gov.br"                      ).save senha: "_001329"
(Usuario.new nome_usuario: "p001377" , nome: "Leonardo Ataíde Lemos"                        , email: "leonardo.lemos@prodam.am.gov.br"                   ).save senha: "_001377"
(Usuario.new nome_usuario: "p001332" , nome: "Priscila da Silva de Britto"                  , email: "priscila.britto@prodam.am.gov.br"                  ).save senha: "_001332"
(Usuario.new nome_usuario: "p001403" , nome: "Rafael Barros Ramos"                          , email: "rafael.ramos@prodam.am.gov.br"                     ).save senha: "_001403"
(Usuario.new nome_usuario: "p001001" , nome: "Adílio dos Santos Moreira"                    , email: "adilio@prodam.am.gov.br"                           ).save senha: "_001001"
(Usuario.new nome_usuario: "p000994" , nome: "Anderson Abreu do Nascimento"                 , email: "anderson.abreu@prodam.am.gov.br"                   ).save senha: "_000994"
(Usuario.new nome_usuario: "p000677" , nome: "Ari Ramos Libório"                            , email: "liborio@prodam.am.gov.br"                          ).save senha: "_000677"
(Usuario.new nome_usuario: "p001155" , nome: "Diovane Monteiro de Sousa"                    , email: "diovane@prodam.am.gov.br"                          ).save senha: "_001155"
(Usuario.new nome_usuario: "p000818" , nome: "João de Deus Marcião Pereira"                 , email: "jmarciao@prodam.am.gov.br"                         ).save senha: "_000818"
(Usuario.new nome_usuario: "p001258" , nome: "Manuel Antonio Trindade"                      , email: "manuel.trindade@prodam.am.gov.br"                  ).save senha: "_001258"
(Usuario.new nome_usuario: "p001353" , nome: "Maria Aparecida Rodrigues da Silva Lima"      , email: "aparecida@prodam.am.gov.br"                        ).save senha: "_001353"
(Usuario.new nome_usuario: "p000586" , nome: "Milene Duarte de Oliveira"                    , email: "mileneduarte@prodam.am.gov.br"                     ).save senha: "_000586"
(Usuario.new nome_usuario: "p000471" , nome: "Carlos Flávio Barbosa Pinto Charchar"         , email: "cflavio@prodam.am.gov.br"                          ).save senha: "_000471"
(Usuario.new nome_usuario: "p000378" , nome: "Furtunato Alves dos Santos Filho"             , email: "fortunato@prodam.am.gov.br"                        ).save senha: "_000378"
(Usuario.new nome_usuario: "p000566" , nome: "Marilane Pessôa Campos"                       , email: "marilane@prodam.am.gov.br"                         ).save senha: "_000566"
(Usuario.new nome_usuario: "p000835" , nome: "Roberto Júlio Lima e Silva"                   , email: "roberto.julio@prodam.am.gov.br"                    ).save senha: "_000835"
(Usuario.new nome_usuario: "p000785" , nome: "Rosana Maria Martins Reis"                    , email: "rosana@prodam.am.gov.br"                           ).save senha: "_000785"
(Usuario.new nome_usuario: "p000686" , nome: "Rozimar da Silva Alves"                       , email: "rozimar@prodam.am.gov.br"                          ).save senha: "_000686"
(Usuario.new nome_usuario: "p000333" , nome: "Sivonete Vidal Fernandes"                     , email: "sivonete@prodam.am.gov.br"                         ).save senha: "_000333"
(Usuario.new nome_usuario: "p001114" , nome: "Uitu Costa Menezes de Souza"                  , email: "uitu@prodam.am.gov.br"                             ).save senha: "_001114"
(Usuario.new nome_usuario: "p000440" , nome: "Vera Núbia da Silva"                          , email: "vera.nubia@prodam.am.gov.br"                       ).save senha: "_000440"
(Usuario.new nome_usuario: "p000774" , nome: "Waldeniza Machado de Alencar"                 , email: "waldeniza@prodam.am.gov.br"                        ).save senha: "_000774"
(Usuario.new nome_usuario: "p001301" , nome: "Bruno Rebelo Lobato"                          , email: "blobato@prodam.am.gov.br"                          ).save senha: "_001301"
(Usuario.new nome_usuario: "p001130" , nome: "Haroldo de Souza Cohen Monteiro Junior"       , email: "haroldojr@prodam.am.gov.br"                        ).save senha: "_001130"
(Usuario.new nome_usuario: "p001230" , nome: "Jeimy Lima de Oliveira"                       , email: "jeimy@prodam.am.gov.br"                            ).save senha: "_001230"
(Usuario.new nome_usuario: "p001408" , nome: "Marcio Ferreira Mota"                         , email: "marcio.mota@prodam.am.gov.br"                      ).save senha: "_001408"
(Usuario.new nome_usuario: "p001281" , nome: "Ronildo Mourão de Albuquerque"                , email: "ronildo@prodam.am.gov.br"                          ).save senha: "_001281"
(Usuario.new nome_usuario: "p001444" , nome: "Taianne Mafra da Silva"                       , email: "taianne.mafra@prodam.am.gov.br"                    ).save senha: "_001444"
(Usuario.new nome_usuario: "p001380" , nome: "Alessandra  Souza Machado"                    , email: "asouza@prodam.am.gov.br"                           ).save senha: "_001380"
(Usuario.new nome_usuario: "p001204" , nome: "Daniel Ribeiro da Costa Gadelha"              , email: "danielgadelha@prodam.am.gov.br"                    ).save senha: "_001204"
(Usuario.new nome_usuario: "p000487" , nome: "Eline Maria de Xerez Vieiralves"              , email: "eline@prodam.am.gov.br"                            ).save senha: "_000487"
(Usuario.new nome_usuario: "p000676" , nome: "Evelyn Burgers Bueno de Carvalho"             , email: "evelyn@prodam.am.gov.br"                           ).save senha: "_000676"
(Usuario.new nome_usuario: "p001260" , nome: "Islo Marques Setubal"                         , email: "islo@prodam.am.gov.br"                             ).save senha: "_001260"
(Usuario.new nome_usuario: "p001146" , nome: "Israel Fernandes Bezerra dos Santos"          , email: "israel@prodam.am.gov.br"                           ).save senha: "_001146"
(Usuario.new nome_usuario: "p001364" , nome: "Jônatas Costa de Oliveira"                    , email: "jonatas@prodam.am.gov.br"                          ).save senha: "_001364"
(Usuario.new nome_usuario: "p000338" , nome: "José Luiz Abreu da Silva"                     , email: "abreu@prodam.am.gov.br"                            ).save senha: "_000338"
(Usuario.new nome_usuario: "p001229" , nome: "Laurinex da Silva Souza"                      , email: "laurinex@prodam.am.gov.br"                         ).save senha: "_001229"
(Usuario.new nome_usuario: "p001164" , nome: "Milton Macena Ramos de Lima"                  , email: "milton@prodam.am.gov.br"                           ).save senha: "_001164"
(Usuario.new nome_usuario: "p001271" , nome: "Paulo Monteiro da Silva"                      , email: "paulo.monteiro@prodamnet.com.br"                   ).save senha: "_001271"
(Usuario.new nome_usuario: "p001292" , nome: "Theilon Christian Feitosa das Neves"          , email: "theilon@prodamnet.com.br"                          ).save senha: "_001292"
(Usuario.new nome_usuario: "p000755" , nome: "Eloíza Maria dos Santos Pinheiro"             , email: "eloiza@prodam.am.gov.br"                           ).save senha: "_000755"
(Usuario.new nome_usuario: "p001413" , nome: "Hiago Dias Costa"                             , email: "hiago.costa@prodam.am.gov.br"                      ).save senha: "_001413"
(Usuario.new nome_usuario: "p000041" , nome: "Maria Amélia Gadelha de Oliveira"             , email: "prodam@prodam.am.gov.br"                           ).save senha: "_000041"
(Usuario.new nome_usuario: "p000420" , nome: "Maria José Dantas Rodrigues"                  , email: "mariajose@prodam.am.gov.br"                        ).save senha: "_000420"
(Usuario.new nome_usuario: "p001172" , nome: "Alessandro Carvalho de Melo"                  , email: "alessandro@prodam.am.gov.br"                       ).save senha: "_001172"
(Usuario.new nome_usuario: "p001278" , nome: "Chrystiano da Rocha Filgueiras"               , email: "cfilgueiras@prodam.am.gov.br"                      ).save senha: "_001278"
(Usuario.new nome_usuario: "p000917" , nome: "José Lincoln Alves de Lucena"                 , email: "lincoln@prodam.am.gov.br"                          ).save senha: "_000917"
(Usuario.new nome_usuario: "p001289" , nome: "Lucas de Andrade Miranda da Silva"            , email: "lucas@prodam.am.gov.br"                            ).save senha: "_001289"
(Usuario.new nome_usuario: "p001152" , nome: "Alessandro Marinho Aguiar"                    , email: "aguiar@prodam.am.gov.br"                           ).save senha: "_001152"
(Usuario.new nome_usuario: "p000573" , nome: "Areolino da Silva Santana"                    , email: "areolino@prodam.am.gov.br"                         ).save senha: "_000573"
(Usuario.new nome_usuario: "p000807" , nome: "Daniel Veloso Soares"                         , email: "daniel@prodam.am.gov.br"                           ).save senha: "_000807"
(Usuario.new nome_usuario: "p000223" , nome: "Denilze Malcher Monteiro da Silva"            , email: "denilze@prodam.am.gov.br"                          ).save senha: "_000223"
(Usuario.new nome_usuario: "p001132" , nome: "Djalma Silva de Souza"                        , email: "djalma@prodam.am.gov.br"                           ).save senha: "_001132"
(Usuario.new nome_usuario: "p001277" , nome: "Edistone da Silva Carvalho"                   , email: "edistone@prodam.am.gov.br"                         ).save senha: "_001277"
(Usuario.new nome_usuario: "p001254" , nome: "Edna Maria Souza de Barros"                   , email: "edna@prodam.am.gov.br"                             ).save senha: "_001254"
(Usuario.new nome_usuario: "p001228" , nome: "Elissa Mara Amorim de Sena"                   , email: "elissa.mara@prodam.am.gov.br"                      ).save senha: "_001228"
(Usuario.new nome_usuario: "p000262" , nome: "João Batista Lima Monteiro"                   , email: "jbatista@prodam.am.gov.br"                         ).save senha: "_000262"
(Usuario.new nome_usuario: "p000827" , nome: "Pedro Carvalho Barros Filho"                  , email: "pedrob@prodam.am.gov.br"                           ).save senha: "_000827"
(Usuario.new nome_usuario: "p001131" , nome: "Valeriana Paes Pinheiro"                      , email: "valeriana.pinheiro@prodam.am.gov.br"               ).save senha: "_001131"
(Usuario.new nome_usuario: "p001265" , nome: "Vivaldo Batista Pereira"                      , email: "vivaldopereira@prodam.am.gov.br"                   ).save senha: "_001265"
(Usuario.new nome_usuario: "p001025" , nome: "Crinnger Fagundes de Oliveira"                , email: "crinnger@prodam.am.gov.br"                         ).save senha: "_001025"
(Usuario.new nome_usuario: "p000987" , nome: "Douglas Henrique Geraldes de Menezes"         , email: "douglas@prodam.am.gov.br"                          ).save senha: "_000987"
(Usuario.new nome_usuario: "p001133" , nome: "Evelyne Wanderley de Siqueira"                , email: "evelyne@prodam.am.gov.br"                          ).save senha: "_001133"
(Usuario.new nome_usuario: "p000545" , nome: "José Neozelídio dos Santos Filho"             , email: "santos@prodam.am.gov.br"                           ).save senha: "_000545"
(Usuario.new nome_usuario: "p001067" , nome: "Márcio Amoedo da Silva"                       , email: "amoedo@prodam.am.gov.br"                           ).save senha: "_001067"
(Usuario.new nome_usuario: "p000649" , nome: "Talismã de Andriola Tabal"                    , email: "ttabal@prodam.am.gov.br"                           ).save senha: "_000649"
(Usuario.new nome_usuario: "p001282" , nome: "Waldir Albuquerque Calmont"                   , email: "waldir@prodam.am.gov.br"                           ).save senha: "_001282"
(Usuario.new nome_usuario: "p001221" , nome: "Cehasli de Castro do Nascimento"              , email: "cehasli@prodam.am.gov.br"                          ).save senha: "_001221"
(Usuario.new nome_usuario: "p001206" , nome: "Mario Jorge da Silva Maciel"                  , email: "mjorge@prodam.am.gov.br"                           ).save senha: "_001206"
(Usuario.new nome_usuario: "p001242" , nome: "Paulo Bruno Batista de Sena"                  , email: "paulo.sena@prodam.am.gov.br"                       ).save senha: "_001242"
(Usuario.new nome_usuario: "p001297" , nome: "Merylim Costa da Cunha"                       , email: "merylim@prodam.am.gov.br"                          ).save senha: "_001297"
(Usuario.new nome_usuario: "p001414" , nome: "Ronne dos Santos Souza"                       , email: "ronne.souza@prodam.am.gov.br"                      ).save senha: "_001414"
(Usuario.new nome_usuario: "p001365" , nome: "Ewerton Hiroshi de Souza Haji"                , email: "ewerton@prodam.am.gov.br"                          ).save senha: "_001365"
(Usuario.new nome_usuario: "p001161" , nome: "Kleitor Franklint Correa de Araújo"           , email: "kleitor@prodam.am.gov.br"                          ).save senha: "_001161"
(Usuario.new nome_usuario: "p001445" , nome: "Adônis Pinto Figueiredo"                      , email: "adonis@prodam.am.gov.br"                           ).save senha: "_001445"
(Usuario.new nome_usuario: "p001137" , nome: "Alexandre Braga Damasceno"                    , email: "alexandrebd@prodam.am.gov.br"                      ).save senha: "_001137"
(Usuario.new nome_usuario: "p001436" , nome: "Brunno José Costa Batista"                    , email: "brunnobatista@prodam.am.gov.br"                    ).save senha: "_001436"
(Usuario.new nome_usuario: "p001435" , nome: "Bruno Machado Moreira"                        , email: "brunomachado@prodam.am.gov.br"                     ).save senha: "_001435"
(Usuario.new nome_usuario: "p000966" , nome: "Gilson Teixeira de Souza"                     , email: "teixeira@prodam.am.gov.br"                         ).save senha: "_000966"
(Usuario.new nome_usuario: "p001286" , nome: "João Leno Pereira da Silva"                   , email: "leno@prodam.am.gov.br"                             ).save senha: "_001286"
(Usuario.new nome_usuario: "p001291" , nome: "Kleverson Ferreira Santana"                   , email: "kleverson@prodamnet.com.br"                        ).save senha: "_001291"
(Usuario.new nome_usuario: "p001433" , nome: "Leandro Mery de Almeida Freitas"              , email: "leandromery@prodam.am.gov.br"                      ).save senha: "_001433"
(Usuario.new nome_usuario: "p000290" , nome: "Agostinho de Paiva Martins"                   , email: "p000290-noemail@prodam.am.gov.br"                  ).save senha: "_000290"
(Usuario.new nome_usuario: "p000918" , nome: "Ailton Alves de Araújo"                       , email: "p000918-noemail@prodam.am.gov.br"                  ).save senha: "_000918"
(Usuario.new nome_usuario: "p000916" , nome: "Carlos Augusto Paes dos Santos"               , email: "p000916-noemail@prodam.am.gov.br"                  ).save senha: "_000916"
(Usuario.new nome_usuario: "p001247" , nome: "Cássia Martins Lima"                          , email: "cassia@prodam.am.gov.br"                           ).save senha: "_001247"
(Usuario.new nome_usuario: "p000748" , nome: "Francinete Azevedo Cavalcante"                , email: "francinete.cavalcante@prodam.am.gov.br"            ).save senha: "_000748"
(Usuario.new nome_usuario: "p001102" , nome: "Gessonei Mendonça Melo"                       , email: "gessonei@prodam.am.gov.br"                         ).save senha: "_001102"
(Usuario.new nome_usuario: "p001263" , nome: "Helena de Castro Monteiro"                    , email: "helena@prodam.am.gov.br"                           ).save senha: "_001263"
(Usuario.new nome_usuario: "p000643" , nome: "Ivan Martins de Paula"                        , email: "p000643-noemail@prodam.gov.am.br"                  ).save senha: "_000643"
(Usuario.new nome_usuario: "p000155" , nome: "José Ferreira da Silva"                       , email: "p000155-noemail@prodam.am.gov.br"                  ).save senha: "_000155"
(Usuario.new nome_usuario: "p000816" , nome: "Josenan de Alencar Leão"                      , email: "p000816-noemail@prodam.am.gov.br"                  ).save senha: "_000816"
(Usuario.new nome_usuario: "p000792" , nome: "Lana Isley Castelo Branco Affonso da Silva"   , email: "p000792-noemail@prodam.am.gov.br"                  ).save senha: "_000792"
(Usuario.new nome_usuario: "p001426" , nome: "Larissa Aleixo Braga"                         , email: "larissa.aleixo@prodam.am.gov.br"                   ).save senha: "_001426"
(Usuario.new nome_usuario: "p000671" , nome: "Luiz Carlos Coêlho da Silva"                  , email: "p000671-noemail@prodam.am.gov.br"                  ).save senha: "_000671"
(Usuario.new nome_usuario: "p000767" , nome: "Maria Izabel Caçula Pereira"                  , email: "p000767-noemail@prodam.gov.am.br"                  ).save senha: "_000767"
(Usuario.new nome_usuario: "p000937" , nome: "Pedro Fernandes de Jesus"                     , email: "p000937-noemail@prodam.am.gov.br"                  ).save senha: "_000937"
(Usuario.new nome_usuario: "p000326" , nome: "Vânia Maria  da Silva Frota"                  , email: "p000326-noemail@prodam.am.gov.br"                  ).save senha: "_000326"
(Usuario.new nome_usuario: "p000639" , nome: "Wagner Elias do Cazal"                        , email: "procuro@prodam.gov.am.br"                          ).save senha: "_000639"
(Usuario.new nome_usuario: "p001411" , nome: "Diego Carmo da Costa"                         , email: "diego.costa@prodam.am.gov.br"                      ).save senha: "_001411"
(Usuario.new nome_usuario: "p000787" , nome: "Hélio Nogueira Damasceno"                     , email: "helio@prodam.am.gov.br"                            ).save senha: "_000787"
(Usuario.new nome_usuario: "p000396" , nome: "Marcondes José Bacal de Araújo"               , email: "p000396-noemail@prodam.am.gov.br"                  ).save senha: "_000396"
(Usuario.new nome_usuario: "p001122" , nome: "Nirley Bindá de Araújo"                       , email: "nirley@prodam.am.gov.br"                           ).save senha: "_001122"
(Usuario.new nome_usuario: "p000820" , nome: "Raimundo Nonato Rosal Leite"                  , email: "afastado@prodam.am.gov.br"                         ).save senha: "_000820"
(Usuario.new nome_usuario: "p001378" , nome: "Reinaldo da Silva Barbosa"                    , email: "reinaldo@prodam.am.gov.br"                         ).save senha: "_001378"
(Usuario.new nome_usuario: "p001338" , nome: "Rubenilson Alves Cordovil"                    , email: "rubenilson@prodam.am.gov.br"                       ).save senha: "_001338"
(Usuario.new nome_usuario: "p000584" , nome: "Fernanda Torres da Silva"                     , email: "fernanda.torres@prodam.am.gov.br"                  ).save senha: "_000584"
(Usuario.new nome_usuario: "p001335" , nome: "Wagner Rodrigues Cunha"                       , email: "wagnerrc@senado.gov.br"                            ).save senha: "_001335"
